name: Deploy Storybook

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'stories/**'
      - '.storybook/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build Storybook
        run: pnpm build-storybook
        
      - name: Copy to docs
        run: |
          rm -rf docs
          cp -r storybook-static docs
          # Создаем .nojekyll файл, чтобы отключить Jekyll
          touch docs/.nojekyll
          
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update storybook"
          git push
